apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-emory-deployment
spec:
  selector:
    matchLabels:
      app: sftp-emory
  replicas: 1
  template:
    metadata:
      labels:
        app: sftp-emory
    spec:
      containers:
      - name: sftp-emory
        image: gcr.io/emeritus-data-science/sftp-gcs:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "500m"
          limits:
            memory: "8Gi"
            cpu: "500m"
        env:
          - name: bucket
            value: "sis_emory"
          - name: port_var
            value: "9022"
          - name: username
            valueFrom:
              secretKeyRef:
                name: sftp-emory-credentials
                key: user
          - name: password
            valueFrom:
              secretKeyRef:
                name: sftp-emory-credentials
                key: password

          - name: sa_key_file_path
            value: /secrets/gcloud-auth/google-cloud-key.json

        volumeMounts:
        - mountPath: /secrets/gcloud-auth
          name: gcloud-auth
          readOnly: true
        ports:
        - containerPort: 9022
      volumes:
      - name: gcloud-auth
        secret:
          secretName: gcloud
        ports:
        - containerPort: 9022

---
apiVersion: v1
kind: Service
metadata:
  name: sftp-emory-service
spec:
  type: LoadBalancer
  loadBalancerIP: 104.154.169.144
  loadBalancerSourceRanges:
    - 34.197.57.115/32
    - 34.197.58.165/32
    - 35.161.51.209/32
    - 160.202.36.37/32     #add local ip to access pod locally
  ports:
  - port: 9022
    targetPort: 9022
    protocol: TCP
  selector:
    app: sftp-emory